### ISSUE TITLE
Make it clearer in the ad-on description how to use it

### ISSUE THREAD

**Issue by Thiagobk122** [simgunz/anki21-addons_fast-cards-reposition#1]
I think that its not working on anki versions 2.11 and 2.12. I tried reinstalling the anki several times, reinstalling the ad-on, but it still does not work and on different computers too. The buttons appear gray and not work, i spend a lot of time, but i got it. Please, explain better to laypeople like me on anki's an ons page, if possible, with images.

**Comment by simgunz** [comment]
Just to be sure, have you sorted the cards by "due date"?

**Comment by Thiagobk122** [comment]
I did it, and got it here, thank you very much. I would like to know if it would be possible for an ad-on add a new card through the browser and that they could stick to the revision line and could be reviewed soon after the other cards.

**Comment by simgunz** [comment]
Sorry I did not read the edited version of the issue. I will improve the add-on page following your suggestion. 

I am not sure I have understood your last comment. You want and add-on that let you add a note to a specific position in the browser? Probably it is possible. Currently right clicking on a note in the browser, there is an entry "Add note". An add-on could add a similar entry "Add note here" that creates a new note, read the due date of the selected note in the browser, and then reposition the note according to this (this last part is exactly what this add-on does).

**Comment by Thiagobk122** [comment]
You understood exactly what I meant. I have been reading several forums looking for solutions to this, and I have seen several people looking for something similar. As I have many notes, it is difficult to go with the "fast cards reposition" one in a tea to get the order I want. The browser caould place a new note wherever we want, respecting the order of the other cards.

**Comment by simgunz** [comment]
See #6
