### ISSUE TITLE
plz help me 

### ISSUE THREAD

**Issue by suusam** [simgunz/anki21-addons_fast-cards-reposition#5]
i am very new to anki and i have absolutely no idea about coding
some error messages keeps appearing whenever I try to add any addon in anki 
it is some internet issue and some violation of protocol 
I added some addon before downloading my deck 
but I can't do anything now 
 and I checked the data as some advice 
FYI I have the new anki version

**Comment by simgunz** [comment]
Contact me in private, you can find my email address on this page: https://ankiweb.net/shared/info/544982740
