### ISSUE TITLE
broken in 2.1.45+

### ISSUE THREAD

**Issue by ijgnd** [simgunz/anki21-addons_fast-cards-reposition#7]
First of all thanks for this really useful add-on.

In 2.1.46 that was recently released I ran into this bug when opening the browser:

    ../544982740/__init__.py", line 157, in <module>
        browser.Browser.onSortChanged, fastRepositionOnSortChanged)
    AttributeError: type object 'Browser' has no attribute 'onSortChanged'

This should be related to https://forums.ankiweb.net/t/add-on-porting-notes-for-anki-2-1-45/11212 

> browser.py has been split into multiple files,

**Comment by simgunz** [comment]
Thanks for the submission I'll try to update it soon.

**Comment by ijgnd** [comment]
just for reference: https://github.com/simgunz/anki21-addons_fast-cards-reposition/pull/8

**Comment by simgunz** [comment]
Fixed by #8
